//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCongNgay
    {
        public int Ma_CCN { get; set; }
        public int Ma_NV { get; set; }
        public int Ma_LCC { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau_CCN { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc_CCN { get; set; }
    
        public virtual LoaiChamCong LoaiChamCong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
