//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuChi
    {
        public int Ma_CTPC { get; set; }
        public int Ma_PC { get; set; }
        public string NoiDung_CTPC { get; set; }
        public Nullable<decimal> TriGia_CTPC { get; set; }
    
        public virtual PhieuChi PhieuChi { get; set; }
    }
}
