//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoUngTuyen
    {
        public int Ma_HSUT { get; set; }
        public int Ma_UV { get; set; }
        public string ViTriCongViec_HSUT { get; set; }
        public Nullable<System.DateTime> NgayNop_HSUT { get; set; }
        public string TrangThai_HSUT { get; set; }
        public byte[] Cv_HSUT { get; set; }
    
        public virtual UngVien UngVien { get; set; }
    }
}
