//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoanLuong
    {
        public int Ma_KL { get; set; }
        public int Ma_LL { get; set; }
        public int Ma_NV { get; set; }
        public Nullable<decimal> SoTien_KL { get; set; }
    
        public virtual LoaiLuong LoaiLuong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
