//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgayNghiLe
    {
        public int Ma_NNL { get; set; }
        public Nullable<System.DateTime> Ngay_NNL { get; set; }
        public string Ten_NNL { get; set; }
    }
}
