//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NghiPhep
    {
        public int Ma_NP { get; set; }
        public int Ma_NV { get; set; }
        public int Ma_KNP { get; set; }
        public Nullable<System.DateTime> NgayBatDau_NP { get; set; }
        public Nullable<System.DateTime> NgayKetThuc_NP { get; set; }
        public string LiDo_NP { get; set; }
    
        public virtual KhoanNghiPhep KhoanNghiPhep { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
