//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyNhanVienEntities : DbContext
    {
        public QuanLyNhanVienEntities()
            : base("name=QuanLyNhanVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangLuong> BangLuong { get; set; }
        public virtual DbSet<ChamCongNgay> ChamCongNgay { get; set; }
        public virtual DbSet<ChiTietPhieuChi> ChiTietPhieuChi { get; set; }
        public virtual DbSet<HoSoUngTuyen> HoSoUngTuyen { get; set; }
        public virtual DbSet<KhoanLuong> KhoanLuong { get; set; }
        public virtual DbSet<KhoanNghiPhep> KhoanNghiPhep { get; set; }
        public virtual DbSet<LichSuNhanVien> LichSuNhanVien { get; set; }
        public virtual DbSet<LoaiChamCong> LoaiChamCong { get; set; }
        public virtual DbSet<LoaiLuong> LoaiLuong { get; set; }
        public virtual DbSet<LoaiNghiPhep> LoaiNghiPhep { get; set; }
        public virtual DbSet<NgayNghiLe> NgayNghiLe { get; set; }
        public virtual DbSet<NghiPhep> NghiPhep { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<PhieuChi> PhieuChi { get; set; }
        public virtual DbSet<PhongBan> PhongBan { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
        public virtual DbSet<UngVien> UngVien { get; set; }
    }
}
