//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int Ma_TK { get; set; }
        public int Ma_NV { get; set; }
        public string TenDangNhap_TK { get; set; }
        public string MatKhau_TK { get; set; }
        public string Quyen_TK { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
