//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UngVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UngVien()
        {
            this.HoSoUngTuyen = new HashSet<HoSoUngTuyen>();
        }
    
        public int Ma_UV { get; set; }
        public string HoTen_UV { get; set; }
        public Nullable<bool> GioiTinh_UV { get; set; }
        public Nullable<System.DateTime> NgaySinh_UV { get; set; }
        public string Email_UV { get; set; }
        public string SoDienThoai_UV { get; set; }
        public string DiaChi_UV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoUngTuyen> HoSoUngTuyen { get; set; }
    }
}
